### ISSUE TITLE
The error message "Unsupported feed version."

### ISSUE THREAD

**Issue by LinxHex** [sekai-soft/rss-lambda#1]
Hello developer, I appreciate your efforts in developing this project to supplement RSSHub's limitations. While using it, I came across an error stating "Unsupported feed version." I would appreciate your guidance on resolving this issue.

The RSS feed URL I am trying to filter is https://www.ithome.com/rss, and the filtering URL I am using is https://rss-lambda.ktachibana.party/rss?url=https%3A%2F%2Fwww.ithome.com%2Frss&op=filter_title_incl_substrs&param=QQ.

**Comment by KTachibanaM** [comment]
I think the website returns 403 to the service because it sends a request to the website with `requests` library's default headers. The content returned by the website is however a valid XML but not an RSS feed, hence `feedparser` reports this is an "unsupported feed version"

I'll make some changes so that headers from the client are carried over to the website, and errors from the website are directly returned to clients.

**Comment by KTachibanaM** [comment]
Fixed in this release https://github.com/k-t-corp/rss-lambda/commit/18dea10e23865b4d90ee0543ee2935d677df9ab5
